parameters:
#    mv_nerds_vote.example.class: MVNerds\VoteBundle\Example

services:
#    mv_nerds_vote.example:
#        class: %mv_nerds_vote.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
