parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     mvnerds
    database_user:     root
    database_password: ~

    mailer_transport:  gmail
#    mailer_host:       
    mailer_user:       mailer@mvnerds.com
    mailer_password:   mailermvnerds2012

    default_locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt
    
    available_languages:	['fr', 'en']
    
    item_builds_path: %kernel.root_dir%/../web/builds
