MVNerdsItemHandler:
    resource: "@MVNerdsItemHandlerBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}

MVNerdsMainBundle_main:
    resource: "@MVNerdsMainBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

MVNerdsLaunchSite_homepage:
    resource: "@MVNerdsLaunchSiteBundle/Controller/"
    type:     annotation
    prefix:   /

mv_nerds_champion_handler:
    resource: "@MVNerdsChampionHandlerBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/champions

mv_nerds_did_you_know:
    resource: "@MVNerdsDidYouKnowBundle/Controller/"
    type:     annotation
    prefix:   /

MVNerdsAdminBundle_homepage:
    resource: "@MVNerdsAdminBundle/Controller/"
    type:     annotation
    prefix:   /administration

mv_nerds_core:
    resource: "@MVNerdsCoreBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
