jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        MVNerds\CoreBundle\Model\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            propel:
                class: MVNerds\CoreBundle\Model\User
                property: username
        in_memory:
            memory:
                users:
                    adminop: { password: ro0nyhanikisuperadminopmvnerds, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
                
        user_area:
            pattern: ^/
            anonymous: ~
            form_login:
                check_path: /summoner/login-check
                login_path: /summoner/login
            logout:
                path:   /summoner/logout
                target: /
            remember_me:
                key: "secretfrommvnerdsro0nyhanikiwelovelolandmvnerds"
                lifetime: 2592000
                path: /
                domain: ~
                
        user_login:
            pattern:  ^/profile
            security: false
            
                
        secured_area:
            pattern:    ^/fr/administration
            form_login:
                check_path: /fr/administration/login_check
                login_path: /fr/administration/login
                default_target_path: /profil
            logout:
                path:   /fr/administration/logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/fr/administration/news, roles: ROLE_NEWSER }
        - { path: ^/fr/administration, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }