jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            propel:
                class: MVNerds\CoreBundle\User
                property: username
        in_memory:
            memory:
                users:
                    adminop: { password: ro0nyhanikisuperadminopmvnerds, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        user_area:
            pattern: ^/
            anonymous: ~
        
        login:
            pattern:  ^/administration/login$
            security: false

        secured_area:
            pattern:    ^/administration
            form_login:
                check_path: /administration/login_check
                login_path: /administration/login
            logout:
                path:   /administration/logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/, roles: ROLE_ADMIN }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }